### ISSUE TITLE
Could you please explain the basic principles in README

### ISSUE THREAD

**Issue by DuTengChong** [deadsy/rvdbg#3]
One answer in this [link](https://github.com/ARMmbed/DAPLink/issues/650) says DAPLink can't support RISC-V. So I'm wondering how this project can do that. However I don't know any Go language. Could you please explain the basic principles？

**Comment by deadsy** [comment]
There are 3 things interacting:

1) The USB device: this converts USB commands from the host system into JTAG signals. In this case the commands are CMSIS-DAP compliant and the firmware on the dongle is DAPLink.
2) JTAG. This is a physical level specification that describes how serial signals can be used to change register contents on a target system.
3) The debug sub-system of the chip. This is defined by RISC-V standard. It describes things like reading/writing memory, single stepping, etc.

So *any* device that can generate JTAG signals can be used to access debug functions on a RISC-V chip. The only requirement is that the debug software can talk to the USB device and get it to generate the correct JTAG signals. I wrote a driver for DAPLink dongles and so my code supports RISC-V debugging:

https://github.com/deadsy/rvdbg/tree/master/itf/daplink

**Comment by DuTengChong** [comment]
Thanks. I get it. So you mean this project will act like OpenOCD+config files, and JLink utility+JLink scripts?

**Comment by deadsy** [comment]
Something like that...
